---
# Source: kwasm-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bogusapp-kwasm-operator
  labels:
    helm.sh/chart: kwasm-operator-0.2.3
    app.kubernetes.io/name: kwasm-operator
    app.kubernetes.io/instance: bogusapp
    app.kubernetes.io/version: "0.2.3"
    app.kubernetes.io/managed-by: Helm
