// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Placeholder for user-supplied values.
values: {
	service: type: "ExternalName"
	service: externalName: "my-internal-site"
}
