---
# Source: booklore/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booklore
  labels:
    helm.sh/chart: booklore-0.1.0
    app.kubernetes.io/name: booklore
    app.kubernetes.io/instance: booklore
    app.kubernetes.io/version: "0.38.2"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: booklore
      app.kubernetes.io/instance: booklore
  template:
    metadata:
      labels:
        helm.sh/chart: booklore-0.1.0
        app.kubernetes.io/name: booklore
        app.kubernetes.io/instance: booklore
        app.kubernetes.io/version: "0.38.2"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: booklore
      initContainers:
        - name: wait-for-database
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for database on port 3306..."
              until nc -z -v -w5 booklore-mariadb 3306; do
                echo "Waiting for database..."
                sleep 2
              done
              echo "Database is available!"
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi
      containers:
        - name: booklore
          image: "booklore/booklore:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 6060
              #protocol: TCP
          env:
            - name: BOOKLORE_PORT
              value: "6060"
            - name: DATABASE_URL
              value: jdbc:mariadb://booklore-mariadb:3306/booklore
            - name: DATABASE_USERNAME
              value: booklore-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booklore-mariadb
                  key: mariadb-password
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: books
              mountPath: /books
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: booklore-data
        - name: books
          persistentVolumeClaim:
            claimName: booklore-books
