---
# Source: booklore/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: booklore
  labels:
    helm.sh/chart: booklore-0.1.0
    app.kubernetes.io/name: booklore
    app.kubernetes.io/instance: booklore
    app.kubernetes.io/version: "0.38.2"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
