---
# Source: booklore/charts/mariadb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: booklore-mariadb
  namespace: "default"
  labels:
    app.kubernetes.io/instance: booklore
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 12.0.2
    helm.sh/chart: mariadb-22.0.0
    app.kubernetes.io/part-of: mariadb
automountServiceAccountToken: false
